### ISSUE TITLE
installation fails due lack of new directories

### ISSUE THREAD

**Issue by Yrosenz** [RandomCoderOrg/fs-manager-udroid#24]
install.sh or udroid.sh should create new dlcache directory /data/data/com.termux/files/usr/var/lib/udroid/dlcache before try to install using new udroid script.
![Screenshot_2022-11-28-08-04-13-399](https://user-images.githubusercontent.com/17320075/204205363-6f413a4e-a3ad-461d-9134-c0070960d413.jpeg)

**Comment by Yrosenz** [comment]
Install.sh at fs-manager-udroid/udroid/src create directory function shows
}

function create_dir() {
    local remove=$1; shift 1
    [[ $remove == 0 ]] && [[ -d $1 ]] && rm -rf $1
    g_spin minidot "Creating directory \"$1\"..." mkdir -p $1    
}
The renove instruction remove the directory right after creating it. i tried commenting out the lines and the directories are created and udroid -i ... installs the requested suite

**Comment by AnninoDr4** [comment]
fixed..
