### ISSUE TITLE
binding error

### ISSUE THREAD

**Issue by Yrosenz** [RandomCoderOrg/fs-manager-udroid#25]
logging in after install result on binding error as follows
~ $ udroid -l udroid-jammy-raw
proot warning: can't sanitize binding "/linkerconfig/ld.config.txt": No such file or directory
groups: cannot find name for group ID 20304
groups: cannot find name for group ID 50304

I have corrected groups warning by touch .hushlogin
Could not find /linkerconfig directory.

**Comment by SaicharanKandukuri** [comment]
[7472c1de821641ddc59fd322dad606a6ea7d4b32] Fixed
