### ISSUE TITLE
add termux/proot 's experimental support for `memfd` -> `--ashmem-memfd`

### ISSUE THREAD

**Issue by SaicharanKandukuri** [RandomCoderOrg/fs-manager-udroid#36]

**Comment by SaicharanKandukuri** [comment]
- https://github.com/termux/proot/issues/258

new arg: `--ashmem-memfd`

> disable by default cause the feature is [experimental](https://github.com/termux/proot/issues/258#issuecomment-1442219423) according to the maintainer

**Comment by AnninoDr4** [comment]
Ill add those ( easy )
