### ISSUE TITLE
How to uninstall udroid?

### ISSUE THREAD

**Issue by yazangamer55** [RandomCoderOrg/fs-manager-udroid#44]
Hello i need to uninstall udroid how could i do it?

**Comment by SaicharanKandukuri** [comment]
```bash
udroid remove <suite>:<distro>
```

**Comment by yazangamer55** [comment]
> ```bash
> udroid remove <suite>:<distro>
> ```

No i know how to uninstall a specifec distro, I need to uninstall whole the udroid so when i type in command line : **udroid**
I need to get the result command not found

**Comment by dvishal485** [comment]
Not really sure if an "uninstall" option exists.

But if you wish to remove `udroid` binary, you can remove it from the installation location. You can check your installation location using `whereis udroid`.

Remember to remove the residual folders.

**Comment by REVOTRONS-XLABS** [comment]
hello it asking for password in vnc server but i don't have any password to authenticate..

**Comment by GitEin11** [comment]
why closed as completed?? OP is asking to uninstall udroid not the "udroid distro"
